import type { GatewayStoreState } from "./types";
import { defaultGatewayConfig } from "./config";

export function createGatewayState(): GatewayStoreState {
  return {
    hosts: [],
    projects: [],
    threads: [],
    models: [],
    loadingModels: false,
    hostConnectionStatuses: {},
    gatewayConfig: defaultGatewayConfig(),
    openingPinnedThreadKey: null,
    runningThreadKeys: [],
    threadStatuses: {},
    activeTurnIdsByThreadKey: {},
    activeTerminalProcessByThreadKey: {},
    threadSettingsByKey: {},
    threadCollaborationModesByKey: {},
    dismissedPlanPromptIdsByKey: {},
    threadGoalsByKey: {},
    threadGoalObservedAtByKey: {},
    threadTokenUsageByKey: {},
    composerDraftsByKey: {},
    threadViews: {},
    subAgentPanels: [],
    activeSubAgentPanelKey: null,
    selectedHostId: null,
    selectedProjectId: null,
    selectedThreadId: null,
    viewEpoch: 0,
    currentThread: null,
    history: null,
    events: [],
    initializing: true,
    loading: false,
    loadingOlderTurns: false,
    olderTurnsCursor: null,
    newerTurnsCursor: null,
    error: null,
    lastEventId: 0,
    scrollToLatestToken: 0,
  };
}
