import type { GatewayStoreState } from "./types";
import { defaultGatewayConfig } from "./config";

export function createGatewayState(): GatewayStoreState {
  return {
    hosts: [],
    projects: [],
    threads: [],
    models: [],
    loadingModels: false,
    hostConnectionStatuses: {},
    gatewayConfig: defaultGatewayConfig(),
    openingPinnedThreadKey: null,
    runningThreadKeys: [],
    threadStatuses: {},
    threadSettingsByKey: {},
    threadTokenUsageByKey: {},
    composerDraftsByKey: {},
    pendingSteersByKey: {},
    threadSnapshots: {},
    selectedHostId: null,
    selectedProjectId: null,
    selectedThreadId: null,
    viewEpoch: 0,
    currentThread: null,
    history: null,
    events: [],
    status: null,
    initializing: true,
    loading: false,
    loadingOlderTurns: false,
    olderTurnsCursor: null,
    newerTurnsCursor: null,
    error: null,
    realtimeSocket: null,
    realtimeSocketConnected: false,
    realtimeSocketReconnectTimer: null,
    realtimeSocketReconnectAttempt: 0,
    realtimeSocketGeneration: 0,
    realtimeHostLifecycleSubscribed: false,
    realtimeThreadSubscriptions: {},
    lastEventId: 0,
    scrollToLatestToken: 0,
  };
}
