import type { GatewayStoreState } from "./types";
import { defaultGatewayConfig } from "./config";

export function createGatewayState(): GatewayStoreState {
  return {
    hosts: [],
    projects: [],
    threads: [],
    models: [],
    loadingModels: false,
    hostConnectionStatuses: {},
    gatewayConfig: defaultGatewayConfig(),
    openingPinnedThreadKey: null,
    runningThreadKeys: [],
    threadStatuses: {},
    activeTurnIdsByThreadKey: {},
    activeTerminalProcessByThreadKey: {},
    threadSettingsByKey: {},
    threadCollaborationModesByKey: {},
    dismissedPlanPromptIdsByKey: {},
    threadGoalsByKey: {},
    threadGoalObservedAtByKey: {},
    threadTokenUsageByKey: {},
    composerDraftsByKey: {},
    submittedTurnRequestsByKey: {},
    threadViews: {},
    subAgentPanels: [],
    activeSubAgentPanelKey: null,
    workspaceTabs: [{ id: "agent", kind: "agent", title: "Agent" }],
    activeWorkspaceTabId: "agent",
    terminalSessions: {},
    selectedHostId: null,
    selectedProjectId: null,
    selectedThreadId: null,
    viewEpoch: 0,
    currentThread: null,
    history: null,
    events: [],
    initializing: true,
    loading: false,
    loadingOlderTurns: false,
    olderTurnsCursor: null,
    newerTurnsCursor: null,
    error: null,
    realtimeSocket: null,
    realtimeSocketConnected: false,
    realtimeSocketReconnectTimer: null,
    realtimeSocketReconnectAttempt: 0,
    realtimeSocketGeneration: 0,
    realtimeHostLifecycleSubscribed: false,
    realtimeThreadSubscriptions: {},
    lastEventId: 0,
    scrollToLatestToken: 0,
  };
}
