<script setup lang="ts">
import ComposerShell from "@/components/chat/composer/ComposerShell.vue";
import { useComposerController } from "@/composables/useComposerController";

const {
  activeEffortCompactLabel,
  activeEffortValue,
  activeModel,
  activeModelLabel,
  activePlanSummary,
  attachedFiles,
  canInterruptTurn,
  canUsePrimaryAction,
  composerInputEnabled,
  deactivatePlanMode,
  effortOptions,
  filteredSlashCommands,
  goalInputActive,
  handleAttachmentChange,
  handleComposerKeydown,
  handlePaste,
  handlePrimaryAction,
  hasComposerInput,
  interruptingTurn,
  isThreadRunning,
  labelEffortOption,
  loadingModels,
  modelOptionValue,
  models,
  planModeActive,
  removeAttachment,
  runSlashCommand,
  selectSlashCommandIndex,
  selectedApprovalMode,
  selectedSlashCommandIndex,
  selectedThreadGoal,
  selectedThreadGoalObservedAt,
  selectedThreadId,
  selectedThreadStatus,
  selectedThreadTokenUsage,
  sendButtonLabel,
  setSelectedApprovalMode,
  setSelectedEffort,
  setSelectedModel,
  slashMenuOpen,
  turnText,
  uploadingAttachments,
} = useComposerController();
</script>

<template>
  <ComposerShell
    v-model="turnText"
    :attached-files="attachedFiles"
    :plan-mode-active="planModeActive"
    :plan-summary="activePlanSummary"
    :goal-input-active="goalInputActive"
    :goal="selectedThreadGoal"
    :goal-observed-at="selectedThreadGoalObservedAt"
    :slash-menu-open="slashMenuOpen"
    :filtered-slash-commands="filteredSlashCommands"
    :selected-slash-command-index="selectedSlashCommandIndex"
    :composer-input-enabled="composerInputEnabled"
    :uploading-attachments="uploadingAttachments"
    :selected-thread-id="selectedThreadId"
    :selected-approval-mode="selectedApprovalMode"
    :selected-thread-token-usage="selectedThreadTokenUsage"
    :models="models"
    :loading-models="loadingModels"
    :active-model="activeModel"
    :active-model-label="activeModelLabel"
    :active-effort-value="activeEffortValue"
    :active-effort-compact-label="activeEffortCompactLabel"
    :effort-options="effortOptions"
    :label-effort-option="labelEffortOption"
    :model-option-value="modelOptionValue"
    :has-composer-input="hasComposerInput"
    :is-thread-running="isThreadRunning"
    :can-interrupt-turn="canInterruptTurn"
    :can-use-primary-action="canUsePrimaryAction"
    :interrupting-turn="interruptingTurn"
    :selected-thread-status="selectedThreadStatus"
    :send-button-label="sendButtonLabel"
    @deactivate-plan="deactivatePlanMode"
    @hover-slash-command="selectSlashCommandIndex"
    @select-slash-command="runSlashCommand"
    @attachment-change="handleAttachmentChange"
    @paste="handlePaste"
    @remove-attachment="removeAttachment"
    @keydown="handleComposerKeydown"
    @primary-action="handlePrimaryAction"
    @update-selected-approval-mode="setSelectedApprovalMode"
    @select-model="setSelectedModel"
    @select-effort="setSelectedEffort"
  />
</template>
